# Generated by Django 5.2.12 on 2026-04-05 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metadata",
            name="size",
        ),
        migrations.RemoveField(
            model_name="metadata",
            name="source",
        ),
        migrations.AddField(
            model_name="metadata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadata",
            name="entity_id",
            field=models.CharField(default="test", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadata",
            name="protocol",
            field=models.CharField(
                choices=[("MQTT", "MQTT"), ("MODBUS", "Modbus TCP")],
                default="MQTT",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
